// <auto-generated />
namespace ERPv1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WarenAnpassung2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WarenAnpassung2));
        
        string IMigrationMetadata.Id
        {
            get { return "201804010430133_WarenAnpassung2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
